# Generated by Django 3.1.4 on 2022-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=264, unique=True)),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
